apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-testbed-argo-codeready
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: https://github.com/ably77/openshift-testbed-argo-codeready
