apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-testbed-argo-codeready
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: https://github.com/ably77/openshift-testbed-argo-codeready
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: codeready
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
