apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: create-api-repo-webhook-run
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "ably77"
    - name: GitHubUser
      value: "ably77"
    - name: GitHubRepo
      value: "vote-api"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: http://vote-cicd-eventlistener-pipelines-tutorial.apps.ly-demo.openshiftaws.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
