apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iotdemo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: https://github.com/ably77/openshift-testbed-apps
    targetRevision: HEAD
    path: iotdemo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: iotdemo-app
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  #ignoreDifferences:
  #- group: apps
  #  kind: Deployment
  #  jsonPointers:
  #  - /spec/replicas
  #- group: route.openshift.io
  #  kind: Route
  #  jsonPointers:
  #  - /status
