apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-testbed-airlineprediction
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    # comment out below if in workshop
    repoURL: https://github.com/ably77/openshift-testbed-airlineprediction
    # for use with workshops, uncomment below and replace <YOUR_GITHUB_USER_HERE>
    #repoURL: https://github.com/<YOUR_GITHUB_USER_HERE>/openshift-testbed-argo-iotdemo
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: airlineprediction-stream
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
